### ISSUE TITLE
Blackbird show's balances incorrectly

### ISSUE THREAD

**Issue by NateBrune** [butor/blackbird#8] opened 2015-05-09 14:51 UTC
The images pretty much explain it all.
![](http://i.gyazo.com/05d5881a434de1291a8e83668ae4104a.png)
![](http://i.gyazo.com/8c51ba6db71d8993a71f460f9de60012.png)

Okcoin is accurate, but bitfinex isnt displaying my actual USD balance and is reversing the USD and Bitcoin balances. I hope this makes sense.

**Comment by butor** [comment] 2015-05-09 15:21
You need to have your USD and BTC on your Bitfinex trading account (not exchange account)

**Comment by butor** [comment] 2015-05-09 15:30
Also, if you use $5.00 TEST cash make sure that you have at least $5.00 on your accounts (or use FULL cash instead).
I will add a function that will first verify that your TEST cash matches what you have on your accounts.

**Comment by NateBrune** [comment] 2015-05-10 00:36
![](http://i.gyazo.com/3e2d77eaba1bb53952c6545bd2743a88.png)
![](http://i.gyazo.com/b2603435a5da99af9cf4bc83f3ffe67a.png)

Okay, I understand that I have to have $5 on both accounts, so I will fix okcoin tonight (when I retrieve my other computer) But the balances still dont appear to be showing correctly. (Again, sorry so much pestering you, I really really do appreciate it :100:)

**Comment by butor** [comment] 2015-05-10 14:37
I cannot reproduce your problem. My Bitfinex trading account information is correctly displayed when I start Blackbird. Are you sure that in _bitfinex.cpp_ you are using the following format:
```C++
#define API_HEAD "X-BFX-APIKEY:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#define KEY      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```
Note that you need to keep the `X-BFX-APIKEY:` part.

**Comment by NateBrune** [comment] 2015-05-11 00:35
It's most certainly the right information in the fields. After further experimentation I have found this. When USD is put in to deposit I can see it in the BTC field of blackbird, and when BTC is put into exchange is shows up in the USD field. No other configuration shows up in blackbird.
![](http://i.gyazo.com/75802efd7a60070e6cd523f72a098f54.png)
![](http://i.gyazo.com/5303ef011e4037816e6813c031f26c7a.png)

**Comment by butor** [comment] 2015-05-11 01:54
Thank you for your investigation I appreciate it. I just found the cause of the issue and will fix it within the next few days. I'll let you know.

**Comment by butor** [comment] 2015-05-11 02:35
Thank you for your investigation. It looks like the order of JSON arrays elements are not preserved in Bitfinex for some reason. I updated _bitfinex.cpp_ with a fix that should solve your problem. Could you please try again? Thanks

**Comment by NateBrune** [comment] 2015-05-11 11:42
You're the man butor, it works now. Thank you loads! I will continue reporting errors if I find anymore.

**Comment by butor** [comment] 2015-05-11 14:09
Great thanks. I'll close the issue. Yes let me know if you find other issues.

**Closed by butor** 2015-05-11 14:09 UTC
