### ISSUE TITLE
Kraken/Bitfinex error

### ISSUE THREAD

**Issue by kjw1985** [butor/blackbird#41] opened 2016-01-24 12:19 UTC
I have added a kraken and bitfinex account to blackbird.conf, using the following trading parameters:

>__Program parameters__
>DemoMode=false
>UseFullCash=false
>UntouchedCash=0.01
>CashForTesting=15.00
>MaxExposure=25000.00
>MaxLength=5184000
>DebugMaxIteration=3200000
>Verbose=true

>__Strategy parameters__
>GapSec=3.0
>SpreadEntry=0.0070
>SpreadTarget=0.0030
>PriceDeltaLimit=0.10
>TrailingSpreadLim=0.0010
>TrailingSpreadCount=2
>OrderBookFactor=1.5

After some time the following error appears in the log (looks like it is not getting JSON back?):

[ 01/24/2016 10:34:00 ]
   Bitfinex: 	399.10 / 399.17
   Kraken: 	393.13 / 394.46
   ----------------------------
   Kraken/Bitfinex:	 1.18% [target  0.70%, min -2.19%, max  1.51%]   trailing  1.41%  1/2

[ 01/24/2016 10:34:03 ]
   Bitfinex: 	399.10 / 399.17
   Kraken: 	393.13 / 394.46
   ----------------------------
   Kraken/Bitfinex:	 1.18% [target  0.70%, min -2.19%, max  1.51%]   trailing  1.41%  2/2
Error with JSON:
'[' or '{' expected near '<'
Buffer:
<!DOCTYPE html>

<html class="no-js" lang="en"> 

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <meta name="description"
    content="The largest and most advanced crypto-currencies trading platform">
  <meta name="keywords"
    content="bitcoin,exchange,bitcoin exchange,litecoin,margin,trade">

  <title>Bitfinex - Error 404: Page not found</title>

For more log see attached file.
[kraken_bitfinex.txt](https://github.com/butor/blackbird/files/102311/kraken_bitfinex.txt)

Is there any more info you need?

**Comment by butor** [comment] 2016-01-28 04:54
Hi @kjw1985,

Something went wrong after an opportunity has been detected by Blackbird:

```
[ 01/24/2016 10:34:03 ]
   Bitfinex:    399.10 / 399.17
   Kraken:      393.13 / 394.46
   ----------------------------
   Kraken/Bitfinex:	 1.18% [target 0.70%, min -2.19%, max 1.51%]  trailing 1.41%  2/2
```

Next, Blackbird would normally check the order book of Bitfinex to generate a limit price with the function _getLimitPrice()_, and this is where it fails. When you call _getLimitPrice()_ on Bitfinex you get this unexpected and long html response, with elements that I don't seem related, e.g.:

> This feature allows you to set a withdrawal address for crypto-currencies for all your future withdrawals. Nobody will be able to withdraw to another address from your account. You will be able to unlock your address using email confirmation.

Or:

> This position is currently liquidating successfully. Please be patient while the order completes. While the position is liquidating we have disabled the "close" action for this position, which would trigger additional market orders. If you think this is a mistake, you may manually unfreeze this position. This is not advised.

A couple of questions for you:

- On what OS is your Blackbird running?
- Do you have the rights to do _margin_ _trading_ on Bitfinex?
- At the very beginning of the logfile, was Blackbird able to correctly show you what you have on your USD and BTC accounts? It's under the section `[ Current balances ]`.

Thanks

**Comment by kjw1985** [comment] 2016-01-28 08:07
Hi butor,

- I'm running Blackbird on a Arch installation. 
- As far as I know I do have rights to do margin trading on bitfinex, but I will try with a small margin trade.
- At the moment I'm not at the computer, but it provides balances for Kraken and Bitfinex, and a very small amount of BTC (if i remember correctly something like 0.002 or 0.0002). I will update my answer when I'm home.

**Comment by butor** [comment] 2016-01-30 22:57
Hi @kjw1985,

If Blackbird can correctly show you your Bitfinex balances then we know it's not an issue with your credentials. I'm very curious about what's going on. Do you still face the issue? If yes, is it always the exact same one?

I would probably contact the Bitfinex support to ask for assistance as I don't see what can be wrong.

Thanks

**Comment by NateBrune** [comment] 2016-02-02 20:35
I also face this issue. I am running arch linux.

**Comment by butor** [comment] 2016-02-03 02:49
Thanks @NateBrune. Do get that long html response too? And only with Bitfinex? Thanks

**Comment by NateBrune** [comment] 2016-02-03 22:25
oh wow I didnt realize you added the ability to dump the buffer. I will get you a sample (Their isn't a trade every day, as I am sure you know lol) . As far as the rest of the behaviour, I am pretty sure we have the same issue.

**Comment by kjw1985** [comment] 2016-02-04 20:56
Problem happened again today. However I hadn't updated blackbird yet. Did it just now and will run again and hopefully I can provide more information.

**Comment by butor** [comment] 2016-02-05 00:27
Thanks for the feedback @kjw1985 and @natebrune. Looks like it's an issue specific to Arch Linux. I will ask the Bitfinex support to see if they are aware of issues with Arch Linux.

**Comment by Insaned79** [comment] 2016-02-15 08:00
I had the same issue with the Ubuntu 14.04

**Comment by kjw1985** [comment] 2016-02-15 18:04
Hi butor,

The error is still happening. Had some trouble after git pull and make giving a segment fault (if I remember correctly). So created a new folder did a clean clone and make and it worked. However still got a json error. For some reason there is a JSON error (probably something goes wrong in the attempt of making a buy at bitfinex.

I will take a look if I can make an api buy (using pythyon).

**Comment by butor** [comment] 2016-02-16 04:38
Hi @Insaned79 and @kjw1985,

Thanks for the feedback. Do you guys still get the issue with a long html answer, e.g.:

> This feature allows you to set a withdrawal address for crypto-currencies for all your future withdrawals. Nobody will be able to withdraw to another address from your account. You will be able to unlock your address using email confirmation.

If that's the case then I'll open a new ticket with the Bitfinex support. We know it's not an authentication issue but it seems to be something related to the _getLimitPrice()_ function.

Please let me know

**Comment by kjw1985** [comment] 2016-02-17 19:34
@butor  Yes that is part of the message. Did you change anything in the last update concerning this bug? 

I didn't had the time yet to try a API short.

**Comment by butor** [comment] 2016-02-20 16:35
Hi @kjw1985,

No I haven't updated anything regarding that bug. I'm going to contact Bitfinex support to have their input. Thanks.

**Comment by sdrelton** [comment] 2016-02-21 16:04
Hey, I think I've managed to figure out the problem.

When I add the following to curl_fun.cpp before curl_easy_perform is called then the proper JSON is returned. I think that curl is trying to send a POST request here whereas a GET request is what we need.

  // Change to GET request
  if (strcmp(url.c_str(), "https://api.bitfinex.com/v1/book/btcusd") == 0)  {
    curl_easy_setopt(params.curl, CURLOPT_CUSTOMREQUEST, "GET");
  }

Clearly this means including < string.h > to get strcmp too.

**Comment by butor** [comment] 2016-02-22 03:30
Thanks @sdrelton for the workaround. On my side I opened a ticket with the Bitfinex support to understand what's going on with that issue. I'll post the answer here. It the problem seems fixed for you, could you please submit a _pull request_ with your modification so we can test?

Regarding the second issue, the Kraken implementation hasn't been fully validated yet so it might still contain bugs. In your case, it seems that Blackbird tried to send a limit order __0.00__@$430.88 that was rejected because the quantity was empty. I'll take a look. Thanks.

**Comment by sdrelton** [comment] 2016-02-22 06:47
Hey,

I was running with 0 test cash just to figure out what was going on, so that will be the issue with Kraken. I need to tidy up the code a bit (since I added print statements everywhere) but I'll submit a PR then. Hopefully I'll have it done today or tomorrow!

**Comment by sdrelton** [comment] 2016-02-22 12:07
So I've submitted a PR ( #51 ) for getting the Bitfinex data but there is still an issue with Kraken which may/may not be related. I now get this log file:

[ 02/22/2016 12:03:18 ]
   Bitfinex:    437.63 / 437.78
   OKCoin:      437.64 / 437.65
   Kraken:      433.15 / 433.62
   ----------------------------
   OKCoin/Bitfinex:     -0.00% [target  0.80%, min -0.02%, max  0.02%]
   Kraken/Bitfinex:      0.93% [target  0.80%, min  0.76%, max  1.03%]   trailing  0.93%  1/2
[ 02/22/2016 12:03:21 ]
   Bitfinex:    437.63 / 437.78
   OKCoin:      437.64 / 437.65
   Kraken:      433.15 / 433.62
   ----------------------------
   OKCoin/Bitfinex:     -0.00% [target  0.80%, min -0.02%, max  0.02%]
   Kraken/Bitfinex:      0.93% [target  0.80%, min  0.76%, max  1.03%]   trailing  0.93%  2/2
<Bitfinex> Looking for a limit price to fill 0.03 BTC...
<Bitfinex> order book: 0.50@$437.63
[ ENTRY FOUND ]
   Date & Time:       02/22/2016 12:03:21
   Exchange Long:     Kraken (id 2)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        $433.62 (target)
   Price Short:       $437.63 (target)
   Spread:            0.93%
   Cash used:         $13.08 on each exchange
   Exit Target:       -0.27%
<Kraken> Trying to send a "buy" limit order: 0.03 @ $433.62...
{"error": ["EGeneral:Invalid arguments"]}


I'm not sure if this is a separate Kraken issue ( @butor mentioned that it was not fully tested yet ) or whether I have caused this by changing the curl options.

**Comment by butor** [comment] 2016-02-23 05:28
Thanks @sdrelton for the pull request. I will accept it.

Here is the answer from Bitfinex support, which seems in line with your explanation:

_It seems you get a 404 http error returned. This could well be the result of sending a GET request to an API endpoint that needs to be polled via POST._
_When making an authenticated call for instance to `/v1/order/new` the cURL request needs to be sent through POST. If the call is made for a public endpoint - for instance to `/v1/pubticker/btcusd` - the request needs to be GET._

If the problem is fixed for everybody I will close the issue.

If you face a different issue with Kraken, please open a new issue. Thanks.

**Comment by sdrelton** [comment] 2016-02-23 07:03
Hey, thanks for accepting though it was a little premature!

I just tested it out and we actually need to change back to POST when the call is completed so that the next call will also be a POST request.

I've done this in PR #52 

Cheers

**Comment by sdrelton** [comment] 2016-02-23 09:10
So with PR #52 I can now enter the market with Kraken / Bitfinex but leaving the market has the same problem.


[ 02/23/2016 08:33:24 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    417.92 / 417.94
   Kraken:      419.10 / 419.63
   ----------------------------
   Kraken/Bitfinex:     -0.28% [target -0.17%, min -0.48%, max  2.99%]   trailing -0.38%  1/2
[ 02/23/2016 08:33:27 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    417.92 / 417.94
   Kraken:      419.10 / 419.63
   ----------------------------
   Kraken/Bitfinex:     -0.28% [target -0.17%, min -0.48%, max  2.99%]   trailing -0.38%  2/2
<Bitfinex> Looking for a limit price to fill 0.03 BTC...
<Bitfinex> order book: 65.42@$419.00
WARNING: Opportunity found but not enough liquidity. Trade canceled
         Target long price:  419.10, Real long price:  417.93
         Target short price: 417.94, Real short price: 419.00
[ 02/23/2016 08:33:30 IN MARKET: Long Kraken / Short Bitfinex ]
Error with JSON:
'[' or '{' expected near '<'
Buffer:
<!DOCTYPE html>


<html class="no-js" lang="en"> .........


I presume that we are looking for a different URL on Bitfinex which also needs to be a GET request but I haven't had time to check what the URL is. It should be a simple modification to get this working once I know the URL.

Thanks

**Comment by Insaned79** [comment] 2016-02-23 10:23
I'm not sure that I have the same problem, but the program doesn't work for me. That's what happens:
`
[ 02/23/2016 12:38:39 ]
   Bitfinex:    424.10 / 424.63
   OKCoin:      422.50 / 422.52
   Kraken:      419.63 / 420.00
   ----------------------------
   OKCoin/Bitfinex:      0.37% [target  0.80%, min  0.37%, max  0.56%]
   Kraken/Bitfinex:      0.98% [target  0.80%, min  0.98%, max  1.14%]   trailing  1.04%  0/2

[ 02/23/2016 12:38:42 ]
   Bitfinex:    424.10 / 424.63
   OKCoin:      422.50 / 422.52
   Kraken:      419.63 / 420.00
   ----------------------------
   OKCoin/Bitfinex:      0.37% [target  0.80%, min  0.37%, max  0.56%]
   Kraken/Bitfinex:      0.98% [target  0.80%, min  0.98%, max  1.14%]   trailing  1.04%  1/2

[ 02/23/2016 12:38:45 ]
   Bitfinex:    424.10 / 424.49
   OKCoin:      422.51 / 422.52
   Kraken:      419.63 / 420.00
   ----------------------------
   OKCoin/Bitfinex:      0.37% [target  0.80%, min  0.37%, max  0.56%]
   Kraken/Bitfinex:      0.98% [target  0.80%, min  0.98%, max  1.14%]   trailing  1.04%  2/2
Error with JSON:
'[' or '{' expected near '<'
Buffer:
<!DOCTYPE html>


<html class="no-js" lang="en"> 

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
`

**Comment by Insaned79** [comment] 2016-02-23 13:36
After last update, I get this:
`
[ 02/23/2016 16:23:36 ]
   Bitfinex: 	424.53 / 425.06
   OKCoin: 	423.61 / 423.86
   Kraken: 	420.42 / 421.00
   ----------------------------
   OKCoin/Bitfinex:	 0.16% [target  0.80%, min  0.09%, max  0.59%]
   Kraken/Bitfinex:	 0.84% [target  0.80%, min  0.01%, max  1.04%]   trailing  0.85%  2/2
<Bitfinex> Looking for a limit price to fill 0.07 BTC...
<Bitfinex> order book: 3.50@$424.60

[ ENTRY FOUND ]
   Date & Time:       02/23/2016 16:23:36
   Exchange Long:     Kraken (id 2)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        $421.00 (target)
   Price Short:       $424.60 (target)
   Spread:            0.84%
   Cash used:         $27.72 on each exchange
   Exit Target:       -0.36%

<Kraken> Trying to send a "buy" limit order: 0.07 @ $421.00...
{"error": ["EGeneral:Invalid arguments"]}

`

**Comment by butor** [comment] 2016-02-23 13:42
Hi @sdrelton,

Here is what I would propose: changing the function:

```C++
json_t* getJsonFromUrl(Parameters& params, std::string url, std::string postFields)
```

by:

```C++
json_t* getJsonFromUrl(Parameters& params, std::string url, std::string postFields, bool isGetNeeded)
```

The parameter `isGetNeeded` will be `true` whenever the GET parameter is needed, and `false` otherwise. What do you think? Thanks

**Comment by sdrelton** [comment] 2016-02-23 14:02
Hey @butor ,

Yes that sounds like a good idea. In order to check it's working fully we'll have to wait for an opportunity to enter and exit the market so it might be a few days depending on market conditions. I suppose this will involve changing in the other *.cpp files too.


@Insaned79 Yes this is what happened to me: I then realised that I need to change cURL back to POST after getting the data from Bitfinex which I did in PR #52 . This got past the point where your error occurs but then has further problems when trying to exit the market.

**Comment by kjw1985** [comment] 2016-02-23 14:18
@butor and @sdrelton  I would happily help testing, let me know if needed.

**Comment by sdrelton** [comment] 2016-02-23 14:23
@kjw1985 Thanks for the offer! I'm currently working on changing everything as discussed above (it isn't really a lot of work). 

I think we can use http://web-sniffer.net/ to see which of the Bitfinex URLs fail to respond using POST requests (this is how I figured out what was happening previously).

I'll run the modified version with a couple of dollars once I've made the modifications and hopefully see if it's working by the morning assuming the market conditions will let it trade.

**Comment by sdrelton** [comment] 2016-02-23 15:00
Hey all,

So my modifications seem to work so far. I'm currently in the market Kraken / Bitfinex. I'll update everyone and submit a PR if I can exit the market properly too.

Cheers

**Comment by sdrelton** [comment] 2016-02-24 13:40
Hey everyone, I'm having trouble testing this because Kraken keeps blocking my API requests (see issue #53 ). This means I can't tell if I can leave the market correctly too. If anyone else wants to try test then that would be great (you can clone from my fork).

**Comment by kjw1985** [comment] 2016-02-24 13:53
If I have time tonight, I'll compile your version and have a try. As I see from your other ticket I should set the time between requests a little higher?

**Comment by sdrelton** [comment] 2016-02-24 14:03
Hey,

Yes I just ran it with 8 seconds between them but still ran into problems!
<http://www.samrelton.com>

**Comment by kjw1985** [comment] 2016-02-24 14:21
@sdrelton  Which Tier are you?

**Comment by sdrelton** [comment] 2016-02-24 14:38
Tier 2, which is probably why I'm timing out so quickly

**Comment by kjw1985** [comment] 2016-02-24 14:43
Ok I have Tier 3, will try as soon as possible.

**Comment by sdrelton** [comment] 2016-02-24 15:56
@kjw1985 Thanks that would be perfect. I guess I should upgrade my tier too!

**Comment by kjw1985** [comment] 2016-02-25 17:16
@sdrelton I have it running now with a gap of 8 seconds. Let see what happens.

**Comment by sdrelton** [comment] 2016-02-26 10:20
@kjw1985 Great thanks for that information! I still ran into Kraken problems after upgrading my account so I've rewritten the code to only make one API call per tick. I haven't uploaded it to Github yet but will do as soon as I can confirm that it works. I've currently got something running so we'll see how it goes.

**Comment by kjw1985** [comment] 2016-02-26 10:54
Here is part of my log file. Because of the open order I got a repeated message about this. I just closed the order myself and as you can see it will look for exiting possibility (which is not really right, as the action was not fulfilled). Will start another test later today to see if a working order might occur.

`  Kraken/Bitfinex:	 0.77% [target  0.50%, min -0.24%, max  0.87%]   trailing  0.77%  2/2
URL: https://api.kraken.com/0/public/Depth
URL: https://api.bitfinex.com/v1/book/btcusd
<Bitfinex> Looking for a limit price to fill 0.04 BTC...
<Bitfinex> order book: 5.91@$421.20

[ ENTRY FOUND ]
   Date & Time:       02/26/2016 05:27:00
   Exchange Long:     Kraken (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        $418.00 (target)
   Price Short:       $421.20 (target)
   Spread:            0.77%
   Cash used:         $15.00 on each exchange
   Exit Target:       -0.33%

<Kraken> Trying to send a "buy" limit order: 0.04 @ $418.00...
<Kraken> Done (transaction ID: #####)

<Bitfinex> Trying to send a "sell" limit order: 0.04@$421.20...
<Bitfinex> Done (order ID: #####)

Waiting for the two orders to be filled...
{"#####": {"refid": null, "starttm": 0, "userref": null, "vol_exec": "0.00000000", "status": "open", "misc": "", "opentm": 1456460824.1940999, "cost": "0.00000", "descr": {"pair": "XBTUSD", "leverage": "none", "type": "buy", "ordertype": "limit", "order": "buy 0.03588520 XBTUSD @ limit 418.00000", "price2": "0", "price": "418.00000"}, "expiretm": 0, "vol": "0.03588520", "price": "0.00000", "fee": "0.00000", "oflags": "fciq"}}
Order ###### still exists!
Long order on Kraken still open...

<cutout long part of same message's>

{"########": {"refid": null, "starttm": 0, "userref": null, "vol_exec": "0.00000000", "status": "open", "misc": "", "opentm": 1456460824.1940999, "cost": "0.00000", "descr": {"pair": "XBTUSD", "leverage": "none", "type": "buy", "ordertype": "limit", "order": "buy 0.03588520 XBTUSD @ limit 418.00000", "price2": "0", "price": "418.00000"}, "expiretm": 0, "vol": "0.03588520", "price": "0.00000", "fee": "0.00000", "oflags": "fciq"}}
Order ####### still exists!
Long order on Kraken still open...
No order exists
Done

WARNING: 16,200 second(s) too late at 02/26/2016 05:27:08

[ 02/26/2016 09:57:16 IN MARKET: Long Kraken / Short Bitfinex ]
URL: https://api.bitfinex.com/v1/ticker/btcusd
URL: https://api.bitfinex.com/v1/ticker/btcusd
   Bitfinex: 	426.18 / 426.20
URL: https://api.kraken.com/0/public/Ticker
URL: https://api.kraken.com/0/public/Ticker
   Kraken: 	422.73 / 425.14
   ----------------------------
   Kraken/Bitfinex:	 0.82% [target -0.33%, min  0.82%, max  0.82%]

[ 02/26/2016 09:57:24 IN MARKET: Long Kraken / Short Bitfinex ]
URL: https://api.bitfinex.com/v1/ticker/btcusd
URL: https://api.bitfinex.com/v1/ticker/btcusd
   Bitfinex: 	426.18 / 426.21
URL: https://api.kraken.com/0/public/Ticker
URL: https://api.kraken.com/0/public/Ticker
   Kraken: 	422.73 / 425.14
   ----------------------------
   Kraken/Bitfinex:	 0.82% [target -0.33%, min  0.82%, max  0.82%]

[ 02/26/2016 09:57:32 IN MARKET: Long Kraken / Short Bitfinex ]
URL: https://api.bitfinex.com/v1/ticker/btcusd
URL: https://api.bitfinex.com/v1/ticker/btcusd
   Bitfinex: 	426.18 / 426.21
URL: https://api.kraken.com/0/public/Ticker
URL: https://api.kraken.com/0/public/Ticker
   Kraken: 	422.73 / 425.14
   ----------------------------
   Kraken/Bitfinex:	 0.82% [target -0.33%, min  0.82%, max  0.82%]`

**Comment by kjw1985** [comment] 2016-02-28 20:14
A small update: Got it running with a gap of 6 seconds. And I'm in the market at the moment. So far no problems encountered. Just haven't got an exit opportunity yet.

**Comment by sdrelton** [comment] 2016-02-29 09:30
Hey @kjw1985 thanks for the update. I have a version running with 10 sec gap which only calls Kraken once per loop instead of twice ( see #53 ) and it seems to be fine so far. Similarly I haven't had an exit opportunity yet but will update when I do.

**Comment by kjw1985** [comment] 2016-03-04 11:59
@sdrelton Here an update again. Finally an exit opportunity which closed my position. Which gave me a 0.18% profit, using the following settings (time between entering and exit is around 6,5 days):

`# Strategy parameters
GapSec=6.0
SpreadEntry=0.0050
SpreadTarget=0.0020
PriceDeltaLimit=0.20
TrailingSpreadLim=0.0010
TrailingSpreadCount=2
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600`

So your update does work sdrelton. Tonight I will test again with a lower gapsec setting (probably 4 or 3). Maybe if you could update the code on your fork to make less request to Kraken I could test that one with a lower gapsec.

**Comment by sdrelton** [comment] 2016-03-04 14:33
@kjw1985 Brilliant thanks for testing it out! I'll update my fork sometime tomorrow when I get chance and post an update here.

Strangely (even after updating my tier) I'm getting the error (as in #53 )

Error with cURL: SSL connect error
  URL: https://api.kraken.com/0/public/Ticker
  Retry in 2 sec...

But that might just be an issue with my specific API key since I've been temporarily banned quite often whilst testing this stuff. I presume you didn't encounter anything like this?

**Comment by kjw1985** [comment] 2016-03-04 20:50
@sdrelton  I had no such error. While search my logfile I found the following error:

> RL: https://api.kraken.com/0/public/Ticker
> Error with cURL: Timeout was reached
>   URL: https://api.kraken.com/0/public/Ticker
>   Retry in 2 sec...
> Error with JSON:
> '[' or '{' expected near '<'
> Buffer:
> <!DOCTYPE html>
> 
> 
> 
>  <html class="no-js" lang="en-US"> 
> <head>
> 
> 
> <meta http-equiv="set-cookie" content="cf_use_ob=0; expires=Thu, 03-Mar-16 06:21:41 GMT; path=/">
> 
> 
> <title>api.kraken.com | 520: Web server is returning an unknown error</title>
> <meta charset="UTF-8" />
> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
> <meta name="robots" content="noindex, nofollow" />
> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
> 
> <style type="text/css">body{margin:0;padding:0}</style>
> 
> <script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
> <script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>
> 
> </head>
> <body>
> <div id="cf-wrapper">
> 
>     
> 
>     <div id="cf-error-details" class="cf-error-details-wrapper">
>         <div class="cf-wrapper cf-error-overview">
>             <h1>
>               <span class="cf-error-type" data-translate="error">Error</span>
>               <span class="cf-error-code">520</span>
>               <small class="heading-ray-id">Ray ID: 27dafca0288f1467 &bull; 2016-03-03 06:21:11 UTC</small>
>             </h1>
>             <h2 class="cf-subheadline" data-translate="error_desc">Web server is returning an unknown error</h2>
>         </div>
> 
>         <div class="cf-section cf-highlight cf-status-display">
>             <div class="cf-wrapper">
>                 <div class="cf-columns cols-3">
>                   
> <div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
>   <div class="cf-icon-error-container">
>     <i class="cf-icon cf-icon-browser"></i>
>     <i class="cf-icon-status cf-icon-ok"></i>
>   </div>
>   <span class="cf-status-desc" data-translate="browser_desc">You</span>
>   <h3 class="cf-status-name" data-translate="browser_label">Browser</h3>
>   <span class="cf-status-label" data-translate="browser_status_label">Working</span>
> </div>
> 
> <div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
>   <div class="cf-icon-error-container">
>     <i class="cf-icon cf-icon-cloud"></i>
>     <i class="cf-icon-status cf-icon-ok"></i>
>   </div>
>   <span class="cf-status-desc" data-translate="cloud_desc">Amsterdam</span>
>   <h3 class="cf-status-name" data-translate="cloud_label">CloudFlare</h3>
>   <span class="cf-status-label" data-translate="cloud_status_label">Working</span>
> </div>
> 
> <div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
>   <div class="cf-icon-error-container">
>     <i class="cf-icon cf-icon-server"></i>
>     <i class="cf-icon-status cf-icon-error"></i>

But this looks like it is a Cloudfare problem. 

I'm now running with a 4 second gap.

**Comment by butor** [comment] 2016-03-09 14:54
Thanks @sdrelton and @kjw1985 for your troubleshooting on Kraken. Should I merge PR #52?

**Comment by sdrelton** [comment] 2016-03-10 10:32
Hey @butor I still need to upload my version which makes less requests to Kraken but I haven't had a chance to exit the market yet so I can't fully confirm that it's working. I would perhaps wait until that point so we can be sure that it's working as intended.

**Comment by butor** [comment] 2016-03-10 20:41
OK got it. Thanks @sdrelton

**Comment by sdrelton** [comment] 2016-03-11 11:36
@butor @kjw1985 I've now managed to exit the market with no problems and have updated by fork (and the pull request) to incorporate this. If you're happy with the changes then I think we can now merge #52

**Comment by butor** [comment] 2016-03-11 15:55
Thanks @sdrelton. I'll accept the #52 merge.

**Closed** 2016-03-11 15:56 UTC
Labels: bug
