### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by apeiron1** [butor/blackbird#9] opened 2015-07-16 19:23 UTC
The ./blackbird command returns this:
> Blackbird Bitcoin Arbitrage
>Version 0.0.2
>DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK.
>
>[ Targets ]
 >  Spread to enter: 0.30%
>   Spread to exit: -0.40%
>
>[ Current balances ]
>Segmentation fault

What may be causing this fault?

**Comment by NateBrune** [comment] 2015-07-20 18:09
I am also experiencing this issue.

**Comment by apeiron1** [comment] 2015-07-20 18:29
We found a solution, I think the code will be upgraded within 2/3 days by a friend of mine.

**Comment by tytanick** [comment] 2015-07-21 09:31
anyone have issue when new order creates in bitfinex, sometimes i see double or even tripple orders.

**Comment by NateBrune** [comment] 2015-07-25 00:34
apeiron1 any update on the progress? I really want to get it working.

**Comment by butor** [comment] 2015-08-15 15:46
@apeiron1: any news on the fix? I couldn't reproduce your segfault.

@NateBrune: FYI the segfault Apeiron1 had is when the system checks his USD account on Bitfinex:
```c++
availability = atof(json_string_value(json_object_get(root, "usd_balance")));
```
I have never been able to reproduce this issue.

**Comment by apeiron1** [comment] 2015-08-15 15:50
It appears that the segfault was caused by a problem with the API keys, in fact I got it fixed by using new APIs

**Comment by butor** [comment] 2015-08-15 16:27
OK great thanks @apeiron1. I will add a function that checks the validity of the credentials instead of having a segfault.

@NateBrune: do you still get a segfault?

**Comment by NateBrune** [comment] 2015-08-15 21:17
No it was my own stupidity. I didnt verify my account on bitstamp so it caused a seg fault. Another API keys problem :)

**Comment by butor** [comment] 2015-08-16 02:41
OK thanks for the feedback @NateBrune. I will close the issue.

@tytanick: do you still face your issue with double and triple orders? If yes, please open a new issue with the details of the error.

**Closed** 2015-08-16 13:18 UTC
